coverage:
  status:
    project:
      default:
        # Allow coverage to be >= 85% (to account for defensive code)
        # Threshold allows 2% wiggle room from target
        target: 85%
        threshold: 2%
        informational: true  # Don't block CI, just show info
    patch:
      default:
        # Be tolerant on code coverage diff on PRs to limit
        # noisy red coverage status on github PRs.
        target: auto
        threshold: 20%
